# Generated by Django 2.2.1 on 2019-05-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='MUSEUM',
        ),
    ]
