# Generated by Django 2.2.1 on 2019-05-28 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0002_auto_20190528_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museums', to=settings.AUTH_USER_MODEL),
        ),
    ]
