# Generated by Django 2.2.1 on 2019-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_museum_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='DESCRIPTION',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='museum',
            name='PHONE',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='museum',
            name='PHOTOURL',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='museum',
            name='TK',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='museum',
            name='WEBURL',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
